#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd
while IFS=':' read -r username password uid gid info ohome shell; do
    echo "The user $username is part of the $gid gang,"\
	 "$uid's place is protected by the passcode $password,"\
	 "more info about the user here: $info"
done < "/etc/passwd"
