#!/usr/bin/env bash
#checking file exists
name=school
if [ -e $name ]; then
   echo "school file exist"
   exit 1
fi
if [ ! -s $name ]; then
   echo "school file is not empty"
fi
if [ -f $name ]; then
   echo "school is a regular file"
fi
